version: "3"

networks:
  app-network:
    driver: bridge

services:
  # postgres:
  #   image: postgres:11
  #   restart: always
  #   volumes:
  #     - .postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   container_name: flask_postgres
  #   hostname: flask_postgres
  
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  
  flask_app:
    build: ./backend
    env_file:
      - .env
    restart: always
    ports:
      - "5000:5000"
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    # links:
    #   - postgres
    # depends_on:
    #   - postgres 
    container_name: flask_app
  
  react_app:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    links:
      - flask_app
    container_name: react_app
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

