version: '3'

services:
  # frontend:
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   container_name: frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

  backend:
    build: ./backend
    env_file:
      - .env
    restart: always
    container_name: backend

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      # - frontend
      - backend

