version: "3"

services:
  flask_app:
    build: ./backend
    restart: always
    ports:
      - "4000:4000"
      - "5678:5678"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: flask_app
  
  react_app:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    links:
      - flask_app
    container_name: react_app
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true